Added Community Runtime for building OLLAMA LLMs in CML
cloudera/community-ml-runtimes pull request #27
Opened 2024-04-23 07:42 UTC by SuperEllipse

OLLAMA (refer to www.ollama.com)  allows easy ways to set up Local LLMs such as Llama2. By default setting up ollama requires sudo access hence we cannot use default runtimes. This runtime addresses that need. 

This PR is submitted by vishrajagopalan@cloudera.com

2024-04-23 20:40 UTC, peterableda requested changes
Can you remove the files that you don't need?

2024-04-23 20:40 UTC, peterableda commented on ollama/Dockerfile
> +    ML_RUNTIME_EDITION="Standard" \
This is overridden below.

2024-04-23 20:40 UTC, peterableda commented on ollama/Dockerfile
> +ENV ML_RUNTIME_EDITION="Nvidia GPU Ollama" \
NVIDIA is all capital, they are very particular about this. :)

2024-04-23 20:40 UTC, peterableda commented on ollama/Dockerfile
> +    ML_RUNTIME_DESCRIPTION="This Version Includes Cuda Libraries and Ollama" \
CUDA is all capital too.

2024-04-23 20:40 UTC, peterableda commented on ollama/Dockerfile
> +    ML_RUNTIME_SHORT_VERSION="1.2" \
short version should be integer.

2024-04-23 20:40 UTC, peterableda commented on ollama/README.md
> +Ollama provides an easy mechanism to set up local selfhosted / private LLMs and multi-modal Models. This runtime setsup the Ollama binaries, the associated CUDA and recommended python libraries for a
"setsup" typo

2024-04-23 20:40 UTC, peterableda commented on ollama/README.md
> +Ollama cannot be set up by a pip ihstall and binary installation on Linux requires sudo access which is not available by default in a CML Terminal for security reasons.
"ihstall" typo

2024-04-23 20:40 UTC, peterableda commented on ollama/etc/Rprofile.site
> +# Site R configuration.
Why do we need the R files?

2024-04-23 20:40 UTC, peterableda commented on ollama/picture/AddingRuntimeinCML.jpg
Do you have a usage example instead?

2024-04-24 05:39 UTC, SuperEllipse commented on ollama/Dockerfile
> +    ML_RUNTIME_EDITION="Standard" \
Removed ML_RUNTIME_EDITION

2024-04-24 05:41 UTC, SuperEllipse commented on ollama/Dockerfile
> +    ML_RUNTIME_SHORT_VERSION="1.2" \
fixed

2024-04-24 05:47 UTC, SuperEllipse commented on ollama/picture/AddingRuntimeinCML.jpg
The usage example is provided in the Read me. Copying below..

A build is available on dockerhub that can be accessed as follows ( needs docker login) by using the format docker.io/your-dockerimagename-name:tag

A prebuilt version has been uploaded to the Docker hub and can can be accessed as follows

docker.io/superellipse/cml-pbj-cuda-ollama:v1.2

2024-04-24 05:54 UTC, SuperEllipse commented on ollama/etc/Rprofile.site
> +# Site R configuration.
removed R files

2024-04-24 06:11 UTC, SuperEllipse commented on ollama/README.md
> +Ollama cannot be set up by a pip ihstall and binary installation on Linux requires sudo access which is not available by default in a CML Terminal for security reasons.
fixed

2024-04-24 14:21 UTC, peterableda approved these changes

2024-04-24 14:21 UTC, merged